TodoTasks.RazorGUI/Pages/PermissionAdmin/Workspace.cshtml.cs
using TodoTasks.RazorGUI.Extensions;
using TodoTasks.RazorGUI.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Threading.Tasks;
using TodoTasks.Domain.Entities;
using System.Linq;
using TodoTasks.OpenIdConnectAuth.Auth;
using TodoTasks.Application.Comparers;

namespace TodoTasks.RazorGUI.Pages.PermissionAdmin
{
    [Authorize(Policy = Policies.Admin)]
    public class WorkspaceModel : BasePermissionAdminModel
    {

        [BindProperty(SupportsGet = true)]
        public string Sort { get; set; } = "";

        [BindProperty(SupportsGet = true)]
        public string SortOrder { get; set; } = "asc";

        [BindProperty(SupportsGet = true)]
        public string CurrentSort { get; set; } = "";

        public IEnumerable<AppUser> Users { get; set; }
        public WorkspaceModel(ITodoApiClient apiClient) : base(apiClient)
        {
        }

        public async Task OnGet()
        {           
            var admins = await TodoApiClient.SearchUsers(AuthConstants.PermissionType, AuthConstants.UserAdminPermission);
            var appUsers = await TodoApiClient.SearchUsers(AuthConstants.PermissionType, AuthConstants.UserPermission);
            Users = admins.Union(appUsers, new AppUserComparer()).ToList();
            
            if (!string.IsNullOrEmpty(Sort))
            {
                if(Sort == CurrentSort)
                {
                    SortOrder = SortOrder.Equals("asc") ? "desc" : "asc";
                }
                else
                {
                    SortOrder = "asc";
                }
                Users = Users.OrderByString(Sort, SortOrder);
            }
            CurrentSort = Sort;
        }
    }
}

TodoTasks.RazorGUI/Pages/Tasks/AddArea.cshtml.cs
using TodoTasks.RazorGUI.Constants;
using TodoTasks.RazorGUI.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.ComponentModel.DataAnnotations;
using System.Threading.Tasks;
using TodoTasks.OpenIdConnectAuth.Auth;

namespace TodoTasks.RazorGUI.Pages.Tasks
{
    [Authorize(Policy = Policies.Admin)]
    public class AddAreaModel : TasksBaseModel
    {
        public AddAreaModel(IAuthorizationService authService, ITodoApiClient client, IAppSessionHandler appSessionHandler) : base(authService, client, appSessionHandler)
        { }

        [BindProperty, Required, StringLength(50, MinimumLength = 2), Display(Name = "Area name")]
        public string AreaName { get; set; }

        public void OnGet() {}

        public async Task<IActionResult> OnPost()
        {
            if(ModelState.IsValid)
            {
                await TodoApiClient.CreateTodoArea(AreaName, User.Identity.Name);

                AppSessionHandler.DeleteData(AreasKey);
                TempData[ViewDataKeys.SuccessMessage] = $"Area '{AreaName}' created successfully.";
                return RedirectToPage("/Tasks/Workspace");
            }

            return Page();
        }
    }
}

TodoTasks.RazorGUI/Pages/Tasks/AddComment.cshtml.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.Threading.Tasks;
using TodoTasks.Application.TodoComment.Commands;
using TodoTasks.RazorGUI.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using TodoTasks.OpenIdConnectAuth.Auth;

namespace TodoTasks.RazorGUI.Pages.Tasks
{
    [Authorize(Policy = Policies.User)]
    public class AddCommentModel : PageModel
    {
        [BindProperty, Required, HiddenInput]
        public int? TodoId { get; set; }
        [Required, BindProperty(), StringLength(300)]
        public string Comment { get; set; }

        private readonly ITodoApiClient todoApiClient;

        public AddCommentModel(ITodoApiClient todoApiClient)
        {
            this.todoApiClient = todoApiClient;
        }

        public void OnGet([Required]int? id) {
            if (!ModelState.IsValid) throw new NullReferenceException("Cannot write comment. Id is missing.");

            TodoId = id;
        }

        public async Task<IActionResult> OnPost()
        {
            if (!ModelState.IsValid) return Page();

            await todoApiClient.CreateTodoComment(new CreateTodoCommentCommand
            {
                TodoId = TodoId,
                UserId = User.Identity.Name,
                Value = Comment
            });

            return RedirectToPage("/Tasks/EditTodo", new { Id = TodoId });
        }
    }
}

TodoTasks.RazorGUI/Pages/Tasks/AddTag.cshtml.cs
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Threading.Tasks;
using TodoTasks.Application.TodoTag.Commands;
using TodoTasks.RazorGUI.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using TodoTasks.OpenIdConnectAuth.Auth;

namespace TodoTasks.RazorGUI.Pages.Tasks
{
    [Authorize(Policy = Policies.User)]
    public class AddTagModel : PageModel
    {
        [BindProperty(SupportsGet = true), Required, HiddenInput]
        public int? TodoId { get; set; }

        [BindProperty(), Required, DisplayName("Tag Text"), StringLength(20)]
        public string TagText { get; set; }

        private readonly ITodoApiClient todoApiClient;

        public AddTagModel(ITodoApiClient todoApiClient)
        {
            this.todoApiClient = todoApiClient;
        }

        public void OnGet()
        {
            if (!ModelState.IsValid) throw new NullReferenceException("Cannot write comment. Id is missing.");
        }

        public async Task<IActionResult> OnPost()
        {
            if (!ModelState.IsValid) return Page();

            await todoApiClient.CreateTodoTag(new CreateTodoTagCommand
            {
                TodoId = TodoId,
                UserId = User.Identity.Name,
                Value = TagText
            });

            return RedirectToPage("/Tasks/EditTodo", new { Id = TodoId });
        }
    }
}

TodoTasks.RazorGUI/Pages/Tasks/Attachments/AddAttachment.cshtml.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using TodoTasks.Application.Attachment.Commands;
using TodoTasks.OpenIdConnectAuth.Auth;
using TodoTasks.RazorGUI.Interfaces;

namespace TodoTasks.RazorGUI.Pages.Tasks.Attachments
{
    [Authorize(Policy = Policies.User)]
    [RequestSizeLimit(10000000)]
    public class AddAttachmentModel : PageModel
    {
        [Required, BindProperty(SupportsGet = true), HiddenInput]
        public int? TodoId { get; set; }
        [StringLength(50), BindProperty]
        public string Description { get; set; }
        [Required(ErrorMessage = "A file must be selected."), BindProperty, Display(Name = "Attachment")]
        public IFormFile UploadedFile { get; set; }

        private readonly ITodoApiClient _todoClient;

        public AddAttachmentModel(ITodoApiClient todoClient)
        {
            _todoClient = todoClient;
        }

        public void OnGet()
        {
            if (!TodoId.HasValue) throw new ArgumentException("Could add new attachment. Id value is missing.");
        }
        public async Task<IActionResult> OnPost()
        {
            if (!ModelState.IsValid)
                return Page();

            using(var stream = UploadedFile.OpenReadStream())
            {
                var command = new CreateAttachmentCommand
                {
                    FileStream = stream,
                    FileName = UploadedFile.FileName,
                    UserId = User.Identity.Name,
                    FileSize = UploadedFile.Length,
                    FileType = UploadedFile.ContentType,
                    Description = Description,
                    TodoId = TodoId.Value
                };

                var result = await _todoClient.CreateAttachment(command);

                if (result == 0) throw new Exception("Failed to insert file.");
            }
            

            return RedirectToPage("AttachmentManagement", new { TodoId });
        }
    }
}

TodoTasks.RazorGUI/Pages/Tasks/Attachments/AttachmentManagement.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Threading.Tasks;
using TodoTasks.Application.Attachment.Models;
using TodoTasks.OpenIdConnectAuth.Auth;
using TodoTasks.RazorGUI.Interfaces;

namespace TodoTasks.RazorGUI.Pages.Tasks.Attachments
{
    [Authorize(Policy = Policies.User)]
    public class AttachmentManagementModel : PageModel
    {
        [Required, BindProperty(SupportsGet = true), HiddenInput]
        public int? TodoId { get; set; }

        public IEnumerable<AttachmentDto> Attachments { get; set; }

        private readonly ITodoApiClient _todoClient;

        public AttachmentManagementModel(ITodoApiClient todoClient)
        {
            _todoClient = todoClient;
        }

        public async Task OnGet()
        {
            if (!ModelState.IsValid) throw new ArgumentException("Could manage attachments. Id value is missing.");

            Attachments = await _todoClient.GetAttachments(TodoId);
        }

        public async Task<IActionResult> OnPost()
        {
            if (!ModelState.IsValid)
            {
                Attachments = await _todoClient.GetAttachments(TodoId);

                return Page();
            }


            return RedirectToPage("AddAttachmentConfirm");
        }
    }
}

TodoTasks.RazorGUI/Pages/Tasks/Attachments/DeleteAttachment.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System;
using System.ComponentModel.DataAnnotations;
using System.Threading.Tasks;
using TodoTasks.OpenIdConnectAuth.Auth;
using TodoTasks.RazorGUI.Interfaces;

namespace TodoTasks.RazorGUI.Pages.Tasks.Attachments
{
    [Authorize(Policy = Policies.User)]
    public class DeleteAttachmentModel : PageModel
    {
        [BindProperty(SupportsGet = true), Required, HiddenInput]
        public int? AttachmentId { get; set; }
        [Required, BindProperty(SupportsGet = true), HiddenInput]
        public int? TodoId { get; set; }

        private readonly ITodoApiClient _todoClient;

        public DeleteAttachmentModel(ITodoApiClient todoClient)
        {
            _todoClient = todoClient;
        }

        public void OnGet()
        {
            if (!ModelState.IsValid) throw new ArgumentException("Could not delete attachment. Id value is missing.");
        }

        public async Task<IActionResult> OnPost()
        {
            if (!ModelState.IsValid) throw new ArgumentException("Could not delete attachment. Id value is missing.");

            await _todoClient.DeleteAttachment(AttachmentId);

            return RedirectToPage("AttachmentManagement", new { TodoId });
        } 
    }
}

TodoTasks.RazorGUI/Pages/Tasks/Attachments/DownloadAttachment.cshtml.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.Net.Http;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using TodoTasks.OpenIdConnectAuth.Auth;
using TodoTasks.RazorGUI.Interfaces;

namespace TodoTasks.RazorGUI.Pages.Tasks.Attachments
{
    [Authorize(Policy = Policies.User)]
    public class DownloadAttachmentModel : PageModel
    {
        [BindProperty(SupportsGet = true), Required, HiddenInput]
        public int? AttachmentId { get; set; }
        [Required, BindProperty(SupportsGet = true), HiddenInput]
        public int? TodoId { get; set; }

        private readonly ITodoApiClient _todoClient;

        public DownloadAttachmentModel(ITodoApiClient todoClient)
        {
            _todoClient = todoClient;
        }

        public void OnGet()
        {
            if (!ModelState.IsValid) throw new ArgumentException("Could not download attachment. Id value is missing.");
        }

        public async Task<IActionResult> OnPost()
        {
            if (!ModelState.IsValid) throw new ArgumentException("Could not download attachment. Id value is missing.");

            var file = await _todoClient.GetAttachment(AttachmentId);

            using (var client = new HttpClient()) {
                var stream = await client.GetStreamAsync(file.FilePath);

                return new FileStreamResult(stream, file.Type)
                {
                    FileDownloadName = file.Name
                };
            }
        }
    }
}

TodoTasks.RazorGUI/Pages/Tasks/CreateTodo.cshtml.cs
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Threading.Tasks;
using TodoTasks.Application.Todo.Commands;
using TodoTasks.Common;
using TodoTasks.RazorGUI.Attributes;
using TodoTasks.RazorGUI.Constants;
using TodoTasks.RazorGUI.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;
using TodoTasks.Domain.Entities;
using System.Linq;
using TodoTasks.OpenIdConnectAuth.Auth;

namespace TodoTasks.RazorGUI.Pages.Tasks
{
    [Authorize(Policy = Policies.User), ValidArea]
    public class CreateTodoModel : TasksBaseModel
    {       
        [Required, BindProperty, HiddenInput]
        public int? CurrentArea { get; set; }
        [Required, BindProperty, StringLength(100)]
        public string Title { get; set; }
        [Required, BindProperty, StringLength(10000), HiddenInput]
        public string Description { get; set; }
        [BindProperty, StringLength(50), DisplayName("Assigned to")]
        public string AssignedTo { get; set; }
        [BindProperty, Required, DisplayName("Todo type")]
        public int? TodoTypeId { get; set; }
        [BindProperty]
        public bool Notify { get; set; }

        public SelectList Users { get; set; }
        public SelectList TodoTypes { get; set; }

        public CreateTodoModel(ITodoApiClient todoClient, IAuthorizationService authService, ITodoApiClient client, IAppSessionHandler appSessionHandler) : base(authService, client, appSessionHandler)
        {
        }

        public async Task OnGet([Required]int? id)
        {
            if (!ModelState.IsValid) throw new ArgumentNullException("Could not create new Todo. Id value is missing.");
            AppSessionHandler.DeleteData(UsersKey);
            CurrentArea = id;

            Users = await GetUsers();
            TodoTypes = new SelectList((await GetReferenceData())?.Types, "Id", "Name");
        }

        public async Task<IActionResult> OnPost()
        {
            if (!ModelState.IsValid) {

                Users = await GetUsers();
                TodoTypes = new SelectList((await GetReferenceData())?.Types, "Id", "Name");

                return Page();
            }
            
            var model = new CreateTodoCommand
            {
                AssignedTo = AssignedTo,
                Description = Description,
                Title = Title,
                TodoAreaId = CurrentArea,
                Type = (TodoType)TodoTypeId,
                UserId = User.Identity.Name,
                Notify = Notify
            };

            var newTodoId = await TodoApiClient.CreateTodoTask(model);
            TempData[ViewDataKeys.SuccessMessage] = $"Todo task added successfully.";
            return RedirectToPage("/Tasks/EditTodo", new { Id = newTodoId });
        }

        private async Task<SelectList> GetUsers()
        {
            var users = AppSessionHandler.GetData<List<AppUser>>(UsersKey);
            if (users == null)
            {
                var user = await TodoApiClient.SearchUsers(AuthConstants.PermissionType, AuthConstants.UserPermission);
                var admins = await TodoApiClient.SearchUsers(AuthConstants.PermissionType, AuthConstants.UserAdminPermission);
                var allUsers = user.Concat(admins);
                AppSessionHandler.SetData(UsersKey, user.Concat(admins));
                users = allUsers.ToList();
            }

            if (users == null) throw new NullReferenceException("Could not retireve users from user API.");
            var userPermissions = (await TodoApiClient.SearchUsers(PermissionTypes.TodoAreaPermission, CurrentArea.Value.ToString()))?.Select(_ => _.UserName).ToList();
            if (userPermissions == null) throw new NullReferenceException("Could not retireve permissions from API.");

            return new SelectList(users.Where(_ => userPermissions.Contains(_.UserName)), "UserName", "UserName");
        }
    }
}

TodoTasks.RazorGUI/ViewComponents/TodoListViewComponent.cs
using TodoTasks.Application.Todo.Models;
using TodoTasks.RazorGUI.Models;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;

namespace TodoTasks.RazorGUI.ViewComponents
{
    public class TodoListViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke(int areaId, string areaName, List<TodoDto> todos)
        {
            var model = new TodoListComponentModel {
                TodoAreaId = areaId,
                TodoAreaName = areaName,
                Todos = todos
            };

            return View(model);
        }
    }
}

TodoTasks.RazorGUI/Pages/Tasks/AddArea.cshtml
@page
@model TodoTasks.RazorGUI.Pages.Tasks.AddAreaModel
@{
    ViewData["Title"] = "Add new area";
}

<main class="container-fluid main-container">
    <form class="card mt-2" style="max-width: 400px;" method="post">
        <section class="card-header">
            Add new area
        </section>
        <section class="card-body">
            <div class="form-group">
                <label asp-for="@Model.AreaName"></label>
                <input asp-for="@Model.AreaName" class="form-control" />
                <span asp-validation-for="@Model.AreaName" class="form-text text-danger small"></span>
            </div>
        </section>
        <section class="card-footer">
            <button type="submit" class="btn btn-primary">Submit</button>
            <a class="btn btn-secondary" asp-page="/Tasks/Workspace">Cancel</a>
        </section>
    </form>
</main>

TodoTasks.RazorGUI/Pages/Tasks/AddComment.cshtml
@page "{id:int?}"
@model TodoTasks.RazorGUI.Pages.Tasks.AddCommentModel
@{
    ViewData["Title"] = "Add Comment";
}

<main class="container-fluid main-container">
    <form class="card mt-2" style="max-width: 30rem;" method="post">
        <input asp-for="@Model.TodoId" />
        <div class="card-header">Add Comment</div>
        <div class="card-body">
            <div class="form-group">
                <label asp-for="@Model.Comment"></label>
                <textarea class="form-control" asp-for="@Model.Comment"></textarea>
                <span asp-validation-for="@Model.Comment" class="form-text text-danger small"></span>
            </div>            
        </div>
        <div class="card-footer">
            <a class="btn btn-secondary mr-2" asp-page="/Tasks/EditTodo" asp-route-id="@Model.TodoId">Cancel</a>
            <button class="btn btn-primary">Submit</button>
        </div>
    </form>
</main>

TodoTasks.RazorGUI/Pages/Tasks/AddTag.cshtml
@page "{todoId:int?}"
@model TodoTasks.RazorGUI.Pages.Tasks.AddTagModel
@{
    ViewData["Title"] = "Add Tag";
}

<main class="container-fluid main-container">
    <form class="card mt-2" style="max-width: 20rem;" method="post">
        <input asp-for="@Model.TodoId" />
        <div class="card-header">Add Tag</div>
        <div class="card-body">
            <div class="form-group">
                <label asp-for="@Model.TagText"></label>
                <input class="form-control" asp-for="@Model.TagText" />
                <span asp-validation-for="@Model.TagText" class="form-text text-danger small"></span>
            </div>
        </div>
        <div class="card-footer">
            <a class="btn btn-secondary mr-2" asp-page="/Tasks/EditTodo" asp-route-id="@Model.TodoId">Cancel</a>
            <button class="btn btn-primary">Submit</button>
        </div>
    </form>
</main>

TodoTasks.RazorGUI/Pages/Tasks/CreateTodo.cshtml
@page "{id:int?}"
@model TodoTasks.RazorGUI.Pages.Tasks.CreateTodoModel

@{
    ViewData["Title"] = "Create new Todo";
}

@section Styles {
    <link href="https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.11/summernote-bs4.css" rel="stylesheet">
}

<main class="container-fluid main-container">
    <form class="card mt-2" style="max-width: 1000px;" method="post">
        <input asp-for="@Model.CurrentArea" />
        <section class="card-header">
            Create new Todo Task


            <label class="notification-bell-container  float-lg-right " title="Notify assigned user about changes">
                <input asp-for="@Model.Notify" class="notification-bell-input" type="checkbox" />
                <span class="oi oi-bell notification-bell"></span>
            </label>

        </section>
        <section class="card-body">
            <div class="form-group">
                <label asp-for="@Model.Title"></label>
                <input asp-for="@Model.Title" class="form-control" />
                <span asp-validation-for="@Model.Title" class="form-text text-danger small"></span>
            </div>
            <div class="form-group">
                <label asp-for="@Model.AssignedTo"></label>
                <select asp-for="@Model.AssignedTo" asp-items="@Model.Users" class="form-control">
                    <option></option>
                </select>
            </div>
            <div class="form-group">
                <label asp-for="@Model.TodoTypeId"></label>
                <select asp-for="@Model.TodoTypeId" asp-items="@Model.TodoTypes" class="form-control"></select>
            </div>
            <div class="form-group">
                <label asp-for="@Model.Description"></label>
                <textarea id="editor" asp-for="@Model.Description"></textarea>
                <span asp-validation-for="@Model.Description" class="form-text text-danger small"></span>
            </div>
        </section>
        <section class="card-footer">
            <button type="submit" class="btn btn-Success">Save</button>
            <a class="btn btn-secondary" asp-page="/Tasks/Workspace" asp-route-id="@Model.CurrentArea">Cancel</a>
        </section>

    </form>
</main>

@section Scripts {
    <script src="https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.11/summernote-bs4.js"></script>

    <script>
        $(document).ready(function () {
            $('#editor').summernote({
                height: 250,
                toolbar: [
                    // [groupName, [list of button]]
                    ['style', ['bold', 'italic', 'underline', 'clear', 'fontsize', 'fontname', 'color']],                   
                    ['para', ['ul', 'ol', 'paragraph', 'height']],
                    ['height', ['undo', 'redo']]
                ]
            });
        });
    </script>
}

TodoTasks.RazorGUI/Pages/Tasks/DeleteArea.cshtml
@page "{id:int}"
@model TodoTasks.RazorGUI.Pages.Tasks.DeleteAreaModel
@{
    ViewData["Title"] = "Delete area";
}

<main class="container-fluid main-container">
    <form class="card mt-2" style="max-width: 500px;" method="post">
        <input asp-for="@Model.Id" />
        <section class="card-header">
            Delete area
        </section>
        <section class="card-body">
            Are you sure you want to delete area with @Model.AreaName?
        </section>
        <section class="card-footer">
            <button type="submit" class="btn btn-danger">Delete</button>
            <a class="btn btn-secondary" asp-page="/Tasks/Workspace" asp-route-id="@Model.Id">Cancel</a>
        </section>
    </form>
</main>

TodoTasks.RazorGUI/Pages/Tasks/Workspace.cshtml
@page "{id:int?}"
@using TodoTasks.OpenIdConnectAuth.Auth
@using Microsoft.AspNetCore.Authorization
@using System.Text.RegularExpressions
@using System.Net
@inject IAuthorizationService AuthorizationService
@model TodoTasks.RazorGUI.Pages.WorkspaceModel
@{
    ViewData["Title"] = "Workspace";
}
<main class="container-fluid main-container">
    <partial name="_Errors" />
    <div class="row task-container">
        <section class="col-xl-2 col-lg-3 border-right task-area-list">
            @if (Model.IsAdmin)
            {
                <div class="text-center">
                    <a class="btn btn-primary mt-2 mb-2" asp-page="/Tasks/AddArea"><span class="oi oi-plus"></span></a>
                </div>
            }

            <ul class="list-group list-group-flush">
                @if (@Model.Areas != null && @Model.Areas.Any())
                {
                    @foreach (var area in @Model.Areas)
                    {
                        <li class="list-group-item task-area-list-item">
                            <div class="task-area-list-item">
                                <a asp-route-id="@area.TodoAreaId" class="task-area-list-item-link ellipsis">@area.Name</a>

                            </div>
                        </li>
                    }
                }
                else
                {
                    <li class="list-group-item task-area-list-item">No areas to display</li>
                }
            </ul>
        </section>
        <section class="col-xl-10 col-lg-9" style="padding: 0">
            @if (Model.Id.HasValue)
            {
                @*<vc:todo-list area-id="@Model.Id.Value" area-name="@Model.CurrentAreaName" todos="@Model.Todos"></vc:todo-list>*@
                <nav class="navbar navbar-expand-lg navbar-light bg-light ">
                    <b style="max-width: 15rem;" class="navbar-brand ellipsis" title="@Model.CurrentAreaName">
                        @Model.CurrentAreaName
                        @if ((await AuthorizationService.AuthorizeAsync(User, Policies.Admin)).Succeeded)
                        {
                            <span>
                                <a asp-page="EditArea" asp-route-id="@Model.Id"><span class="oi oi-pencil"></span></a>
                                <a asp-page="DeleteArea" asp-route-id="@Model.Id"><span class="oi oi-trash"></span></a>
                            </span>
                        }

                    </b>
                    <div class="navbar-text ml-auto">
                        <a class="btn btn-secondary mr-2 btn-sm text-white" asp-route-id="@Model.Id" asp-route-refresh="true" title="Reload page"><span class="oi oi-reload"></span></a>
                        <a class="btn btn-secondary btn-sm text-white" asp-page="/Tasks/CreateTodo" asp-route-id="@Model.Id" title="Create new todo"><span class="oi oi-plus"></span></a>
                    </div>
                </nav>
                <section>
                    <table class="table table-sm table-light table-striped table-hover">
                        <thead>
                            <tr>
                                <th>ID</th>
                                <th></th>
                                <th>Title</th>
                                <th>Description</th>
                                <th class="single-line">Assigned To</th>
                                <th>Type</th>
                                <th>Status</th>
                                <th>Close</th>
                                <th>Created</th>
                                <th>Updated</th>
                                <th class="single-line">Created by</th>
                                <th class="single-line">Updated by</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model.Todos)
                            {
                                <tr>
                                    <td><a asp-page="/Tasks/EditTodo" asp-route-id="@item.TodoId">@item.TodoId</a></td>
                                    <td></td>
                                    <td style="max-width:5rem;">
                                        <div class="ellipsis">@item.Title</div>
                                    </td>
                                    <td style="max-width:7rem;">
                                        <div class="ellipsis">@WebUtility.HtmlDecode(@Regex.Replace(@item.Description, "<[^>]*(>|$)", string.Empty))</div>
                                    </td>
                                    <td>@item.AssignedTo</td>
                                    <td>@item.Type</td>
                                    <td>@item.Status</td>
                                    <td>@item.CloseReason</td>
                                    <td class="single-line">@item.Created?.ToString("yyyy-MM-dd")</td>
                                    <td class="single-line">@item.Updated?.ToString("yyyy-MM-dd")</td>
                                    <td>@item.CreatedBy</td>
                                    <td>@item.UpdatedBy</td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </section>
            }

        </section>
    </div>

</main>