TodoTasks.RazorGUI/Pages/PermissionAdmin/ConfirmAdd.cshtml.cs
using System.ComponentModel.DataAnnotations;
using System.Threading.Tasks;
using TodoTasks.RazorGUI.Exceptions;
using TodoTasks.RazorGUI.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace TodoTasks.RazorGUI.Pages.PermissionAdmin
{
    public class ConfirmAddModel : BasePermissionAdminModel
    {
        
        [BindProperty(SupportsGet = true), Required, HiddenInput]
        public string UserName { get; set; }
        [BindProperty(SupportsGet = true), Required, HiddenInput]
        public int? AreaId { get; set; }
        [BindProperty(SupportsGet = true), Required, HiddenInput]
        public string AreaName { get; set; }
        public ConfirmAddModel(ITodoApiClient todoApiClient) : base(todoApiClient)
        {}

        public void OnGet()
        {
            if (!ModelState.IsValid) throw new InvalidModelStateException(ModelState, "Failed to show confirm page.");
        }

        public async Task<IActionResult> OnPost()
        {
            if (!ModelState.IsValid) throw new InvalidModelStateException(ModelState, "Failed to add new area permission.");

            await TodoApiClient.CreateAreaPermission(AreaId, UserName);

            return RedirectToPage("/PermissionAdmin/Details", new { UserName });
        }
    }
}

TodoTasks.RazorGUI/Pages/PermissionAdmin/ConfirmRemove.cshtml.cs
using System.ComponentModel.DataAnnotations;
using System.Threading.Tasks;
using TodoTasks.RazorGUI.Exceptions;
using TodoTasks.RazorGUI.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace TodoTasks.RazorGUI.Pages.PermissionAdmin
{
    public class ConfirmRemoveModel : BasePermissionAdminModel
    {
        [BindProperty(SupportsGet = true), Required, HiddenInput]
        public string UserName { get; set; }
        [BindProperty(SupportsGet = true), Required, HiddenInput]
        public int? AreaPermissionId { get; set; }
        [BindProperty(SupportsGet = true), Required, HiddenInput]
        public string AreaName { get; set; }
        public ConfirmRemoveModel(ITodoApiClient todoApiClient) : base(todoApiClient)
        { }

        public void OnGet()
        {
            if (!ModelState.IsValid) throw new InvalidModelStateException(ModelState, "Failed to show confirm page.");
        }

        public async Task<IActionResult> OnPost()
        {
            if (!ModelState.IsValid) throw new InvalidModelStateException(ModelState, "Failed to remove area permission.");

            await TodoApiClient.DeleteAreaPermission(AreaPermissionId, UserName);

            return RedirectToPage("/PermissionAdmin/Details", new { UserName });
        }
    }
}

TodoTasks.RazorGUI/Pages/PermissionAdmin/Details.cshtml.cs
using TodoTasks.Application.TodoArea.Models;
using TodoTasks.RazorGUI.Exceptions;
using TodoTasks.RazorGUI.Interfaces;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Threading.Tasks;
using System.Linq;
using TodoTasks.Domain.Entities;
using TodoTasks.OpenIdConnectAuth.Auth;

namespace TodoTasks.RazorGUI.Pages.PermissionAdmin
{
    public class DetailsModel : BasePermissionAdminModel
    {
        [BindProperty(SupportsGet = true), Required]
        public string UserName { get; set; }
        public IEnumerable<AppPermission> Permissions { get; set; }
        public IEnumerable<TodoAreaDto> AvailableAreas { get; set; }
        public IEnumerable<TodoAreaDto> UserAreas { get; set; }

        public DetailsModel(ITodoApiClient apiClient) : base(apiClient)
        {
        }

        public async Task OnGet()
        {
            if (!ModelState.IsValid) throw new InvalidModelStateException(ModelState);

            var user = await TodoApiClient.GetPermissionUser(UserName);
            Permissions = user.Permissions.Where(_ => _.PermissionName.Equals(PermissionTypes.TodoAreaPermission));
            var areas = await TodoApiClient.GetTodoAreas(new string[] { });
            AvailableAreas = areas.Where(_ => !Permissions.Any(x => x.PermissionValue.Equals(_.TodoAreaId.Value.ToString())));
            UserAreas = areas.Where(_ => Permissions.Any(x => x.PermissionValue.Equals(_.TodoAreaId.Value.ToString())));
        }
    }
}

TodoTasks.RazorGUI/Pages/PermissionAdmin/Workspace.cshtml.cs
using TodoTasks.RazorGUI.Extensions;
using TodoTasks.RazorGUI.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Threading.Tasks;
using TodoTasks.Domain.Entities;
using System.Linq;
using TodoTasks.OpenIdConnectAuth.Auth;
using TodoTasks.Application.Comparers;

namespace TodoTasks.RazorGUI.Pages.PermissionAdmin
{
    [Authorize(Policy = Policies.Admin)]
    public class WorkspaceModel : BasePermissionAdminModel
    {

        [BindProperty(SupportsGet = true)]
        public string Sort { get; set; } = "";

        [BindProperty(SupportsGet = true)]
        public string SortOrder { get; set; } = "asc";

        [BindProperty(SupportsGet = true)]
        public string CurrentSort { get; set; } = "";

        public IEnumerable<AppUser> Users { get; set; }
        public WorkspaceModel(ITodoApiClient apiClient) : base(apiClient)
        {
        }

        public async Task OnGet()
        {           
            var admins = await TodoApiClient.SearchUsers(AuthConstants.PermissionType, AuthConstants.UserAdminPermission);
            var appUsers = await TodoApiClient.SearchUsers(AuthConstants.PermissionType, AuthConstants.UserPermission);
            Users = admins.Union(appUsers, new AppUserComparer()).ToList();
            
            if (!string.IsNullOrEmpty(Sort))
            {
                if(Sort == CurrentSort)
                {
                    SortOrder = SortOrder.Equals("asc") ? "desc" : "asc";
                }
                else
                {
                    SortOrder = "asc";
                }
                Users = Users.OrderByString(Sort, SortOrder);
            }
            CurrentSort = Sort;
        }
    }
}

TodoTasks.RazorGUI/Pages/Tasks/Workspace.cshtml.cs
using TodoTasks.Application.Todo.Models;
using TodoTasks.Application.Todo.Queries;
using TodoTasks.Application.TodoArea.Models;
using TodoTasks.RazorGUI.Attributes;
using TodoTasks.RazorGUI.Interfaces;
using TodoTasks.RazorGUI.Pages.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TodoTasks.Domain.Entities;
using TodoTasks.OpenIdConnectAuth.Auth;

namespace TodoTasks.RazorGUI.Pages
{
    [Authorize(Policy = Policies.User), ValidArea]
    public class WorkspaceModel : TasksBaseModel
    {
        public bool IsAdmin { get; set; }
        public IEnumerable<TodoAreaDto> Areas { get; set; }
        
        public string CurrentAreaName { get; set; }
        public IEnumerable<TodoDto> Todos { get; set; }

        [BindProperty(SupportsGet = true)]
        public TodoFilterSearchQuery SearchModel { get; set; }

        [BindProperty(SupportsGet = true)]
        public int? Id { get; set; }

        [BindProperty(SupportsGet = true)]
        public bool Refresh { get; set; }

        public List<AppUser> Users { get; set; }

        public WorkspaceModel(IAuthorizationService authService, ITodoApiClient client, IAppSessionHandler appSessionHandler) 
            : base(authService, client, appSessionHandler) {
        }
       
        public async Task OnGet()
        {
            IsAdmin = (await AuthService.AuthorizeAsync(User, Policies.Admin)).Succeeded;
            Areas = await GetAreasByPermission();

            if (Areas != null && Areas.Any() && Id.HasValue) CurrentAreaName = Areas.FirstOrDefault(_ => _.TodoAreaId == Id)?.Name;

            if (Id.HasValue)
            {
                if (!SearchModel.CurrentPage.HasValue) SearchModel.CurrentPage = 1;
                if (!SearchModel.PageSize.HasValue) SearchModel.PageSize = 25;
                SearchModel.TodoAreaId = Id;
                var result = await TodoApiClient.FilterTodos(SearchModel);
                if (result != null)
                {
                    Todos = result.Todos;
                    Users = AppSessionHandler.GetData<List<AppUser>>(UsersKey);
                    if(Users == null)
                    {
                        var admins = await TodoApiClient.SearchUsers(AuthConstants.PermissionType, AuthConstants.UserAdminPermission);
                        var appUsers = await TodoApiClient.SearchUsers(AuthConstants.PermissionType, AuthConstants.UserPermission);
                        Users = admins.Concat(appUsers).ToList();                     
                        AppSessionHandler.SetData(UsersKey, Users);
                    }

                    //Users.Add(new UserDto { Id = User.GetUserId(), UserName = User.GetUserName() });
                }                   
            }
        }

        private async Task<IEnumerable<TodoAreaDto>> GetAreasByPermission()
        {
            var user = await TodoApiClient.GetPermissionUser(User.Identity.Name);
            if (user == null) return null;
            var areas = await TodoApiClient.GetTodoAreas(user.Permissions.Where(_ => _.PermissionName.Equals(PermissionTypes.TodoAreaPermission)).Select(_ => _.PermissionValue));
            return areas;
        }
    }
}

TodoTasks.RazorGUI/ViewComponents/IconSortViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace TodoTasks.RazorGUI.ViewComponents
{
    public class IconSortViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke(string propertyName, string sortColumn, string sortOrder)
        {
            return View((propertyName, sortColumn, sortOrder));
        }
    }
}

TodoTasks.RazorGUI/Pages/PermissionAdmin/ConfirmAdd.cshtml
@page
@model TodoTasks.RazorGUI.Pages.PermissionAdmin.ConfirmAddModel
@{
    ViewData["Title"] = "Add Area Permissions";
}

<main class="container-fluid main-container">
    <form class="card mb-2 mt-2" style="max-width: 20rem;" method="post">
        <input asp-for="@Model.UserName" />
        <input asp-for="@Model.AreaName" />
        <input asp-for="@Model.AreaId" />
        <section class="card-header">Confirm add new area permission</section>
        <section class="card-body">
            Do you want to give user '@Model.UserName' permission to '@Model.AreaName'?
        </section>
        <section class="card-footer">
            <button class="btn-primary btn" type="submit">Yes</button>
            <a class="btn-danger btn" asp-page="/PermissionAdmin/Details" asp-route-userName="@Model.UserName">No</a>
        </section>
    </form>
</main>

TodoTasks.RazorGUI/Pages/PermissionAdmin/ConfirmRemove.cshtml
@page
@model TodoTasks.RazorGUI.Pages.PermissionAdmin.ConfirmRemoveModel
@{
    ViewData["Title"] = "Remove Area Permissions";
}

<main class="container-fluid main-container">
    <form class="card mb-2 mt-2" style="max-width: 20rem;" method="post">
        <input asp-for="@Model.AreaPermissionId" />
        <input asp-for="@Model.UserName" />
        <input asp-for="@Model.AreaName" />
        <section class="card-header">Confirm removal of area permission</section>
        <section class="card-body">
            Do you want to remove permission to '@Model.AreaName' from user '@Model.UserName'?
        </section>
        <section class="card-footer">
            <button class="btn-primary btn" type="submit">Yes</button>
            <a class="btn-danger btn" asp-page="/PermissionAdmin/Details" asp-route-userName="@Model.UserName">No</a>
        </section>
    </form>
</main>

TodoTasks.RazorGUI/Pages/PermissionAdmin/Details.cshtml
@page
@model TodoTasks.RazorGUI.Pages.PermissionAdmin.DetailsModel
@{
    ViewData["Title"] = "Details";
}

<main class="container-fluid main-container">
    <section class="card mb-2 mt-2" style="max-width: 30rem;">
        <section class="card-header">Area Permissions for @Model.UserName</section>
        <section class="card-body">
            <div class="form-group">
                <div class="dropdown">                  
                    <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Available area permission
                    </a>

                    <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                        @if (@Model.AvailableAreas != null && @Model.AvailableAreas.Any())
                        {
                            @foreach (var area in @Model.AvailableAreas)
                            {
                                <a class="dropdown-item" 
                                   asp-page="/PermissionAdmin/ConfirmAdd" 
                                   asp-route-areaid="@area.TodoAreaId" 
                                   asp-route-username="@Model.UserName" 
                                   asp-route-areaname="@area.Name">@area.Name</a>
                            }
                        }
                        else
                        {
                            <div class="dropdown-item" >No available area permissions</div>
                        }
                    </div>
                </div>
            </div>
            <div class="form-group">
                <label>Current area permissions</label>
                <ul class="list-group">
                    @if (@Model.UserAreas != null && @Model.UserAreas.Any())
                    {
                        @foreach (var area in @Model.UserAreas)
                        {
                            <li class="list-group-item d-flex justify-content-between align-items-center">
                                @area.Name
                                <a class="badge badge-danger badge-pill" 
                                   asp-page="/PermissionAdmin/ConfirmRemove"
                                   asp-route-username="@Model.UserName" 
                                   asp-route-areaname="@area.Name"
                                   asp-route-AreaPermissionId="@area.TodoAreaId">Remove</a>
                            </li>
                        }
                    }
                    else
                    {
                        <li class="list-group-item d-flex justify-content-between align-items-center">No permissions assigned</li>
                    }

                </ul>
            </div>
            <div >
                <a asp-page="/PermissionAdmin/Workspace">Back to user list</a>
            </div>
        </section>
    </section>
</main>

TodoTasks.RazorGUI/Pages/PermissionAdmin/Workspace.cshtml
@page
@model TodoTasks.RazorGUI.Pages.PermissionAdmin.WorkspaceModel
@{
    ViewData["Title"] = "Area Permissions";
}
<main class="container-fluid main-container">
    <section class="card mb-2 mt-2" style="max-width: 50rem;">
        <div class="card-body">
            <table class="table table-sm table-light table-striped table-hover">
                <thead>
                    <tr>
                        <th>
                            <a asp-page="/PermissionAdmin/Workspace" asp-route-sort="UserName" asp-route-currentsort="@Model.CurrentSort" asp-route-sortorder="@Model.SortOrder">Username</a>
                            <vc:icon-sort property-name="UserName" sort-order="@Model.SortOrder" sort-column="@Model.Sort"></vc:icon-sort>
                        </th>
                        <th>
                            <a asp-page="/PermissionAdmin/Workspace" asp-route-sort="FirstName" asp-route-currentsort="@Model.CurrentSort" asp-route-sortorder="@Model.SortOrder">First name</a>
                            <vc:icon-sort property-name="FirstName" sort-order="@Model.SortOrder" sort-column="@Model.Sort"></vc:icon-sort>
                        </th>
                        <th>
                            <a asp-page="/PermissionAdmin/Workspace" asp-route-sort="LastName" asp-route-currentsort="@Model.CurrentSort" asp-route-sortorder="@Model.SortOrder">Last name</a>
                            <vc:icon-sort property-name="LastName" sort-order="@Model.SortOrder" sort-column="@Model.Sort"></vc:icon-sort>
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var permission in Model.Users)
                    {
                        <tr>
                            <td><a asp-page="/PermissionAdmin/Details" asp-route-userName="@permission.UserName">@permission.UserName</a></td>
                            <td>@permission.FirstName</td>
                            <td>@permission.LastName</td>                            
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </section>
</main>